layer.conf: Add noto-fonts dep on fontconfig to exclude from signatures
This ensures that this package can stay allarch and does not recompile
when machine is changed

Fixes
 === Comparing signatures for task do_package_write_ipk.sigdata between qemux86copy and qemuarm ===
ERROR: noto-fonts different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm

Signed-off-by: Khem Raj <raj.khem@gmail.com>