machine: sama5: Add preferred provider for u-boot
Add the preferred provider for u-boot virtual package and not
only for the bootloader's one.

This is needed by fitImage class, for example, otherwise,
it leads to the following error:

ERROR: Nothing PROVIDES 'u-boot'
ERROR: u-boot was skipped: PREFERRED_PROVIDER_virtual/bootloader set to u-boot-at91, not u-boot
ERROR: Required build target 'virtual/kernel' has no buildable providers.
Missing or unbuildable dependency chain was: ['virtual/kernel', 'u-boot']

See code of meta/classes/kernel-fitimage.bbclass.

Fixes #100.

Signed-off-by: Mylène Josserand <mylene.josserand@bootlin.com>