recipes-support: p11-kit: add native
Addressing the following error
ERROR: Nothing PROVIDES 'p11-kit-native' (but
virtual:native:/work6/kirkstone-yocto/poky/meta/recipes-support/gnutls/gnutls_3.7.4.bb
DEPENDS on or otherwise requires it). Close matches:

Signed-off-by: Dharma Balasubiramani <dharma.b@microchip.com>