linux-mchp: Fix the file path to import patches
Yocto uses a default striplevel=1 to import the patches,
so specify correct path to fetch the patches.

The "devtool modify" fails with the following error
ERROR: Importing patch '0001-dts-include-optee-dtsi.patch' with striplevel '1'
FileNotFoundError(2, 'No such file or directory')

Fixes: 9bd6a63e28de ("optee-bsp: linux-mchp: add optee support")

Signed-off-by: Dharma Balasubiramani <dharma.b@microchip.com>
Acked-by: Hari Prasath Gujulan Elango <Hari.PrasathGE@microchip.com>