qt4: upgrade to 4.8.5
this fix
ERROR: No recipes available for:
  /.../meta-atmel/recipes-qt/qt4/qt4-embedded_4.8.4.bbappend

Signed-off-by: Eric Bénard <eric@eukrea.com>
Signed-off-by: Nicolas Ferre <nicolas.ferre@atmel.com>