egt: Inherit siteinfo
These recipes use SITEINFO_ENDIANNESS, it therefore is required that
they get evaluated before used

Fixes
MACHINE=qemumips bitbake egt-samples-contribution
ERROR: Nothing PROVIDES 'libegt' (but /mnt/b/yoe/master/sources/meta-atmel/recipes-egt/apps/egt-samples-contribution_1.0.bb DEPENDS on or otherwise requires it)
libegt was skipped: Requires little-endian target.
ERROR: Required build target 'egt-samples-contribution' has no buildable providers.
Missing or unbuildable dependency chain was: ['egt-samples-contribution', 'libegt']

Signed-off-by: Khem Raj <raj.khem@gmail.com>