recipes-egt: fix egt-benchmark fetch issue
The egt-benchmark's external dependency
"https://github.com/linux4sam/egt-benchmark/tree/master/external",
doesn't fully initialize while using the git-fetcher, so use gitsm
fetcher instead of git-fetcher.

If the network flag is not set, compilation fails with the following error.
| src/main.cpp:7:10: fatal error: hayai.hpp: No such file or directory
|     7 | #include <hayai.hpp>
|       |          ^~~~~~~~~~~
| compilation terminated.

Replace the workaround changes with the actual fix.
Fixes: f64c31f759b2 ("recipes-egt: egt-thermostat: set network flag")

Signed-off-by: Dharma Balasubiramani <dharma.b@microchip.com>
Reviewed-by: Ludovic Desroches <ludovic.desroches@microchip.com>