egt-media: Use renamed plugin packagename videoconvertscale
since gstreamer 1.22 videoconvert/videoscale plgins were merged into one
and main recipe reflects that, therefore adjust accordingly

Fixes
ERROR: QA Issue: egt-media rdepends on gstreamer1.0-plugins-base-videoconvert, but it isn't a build dependency? [build-deps]
ERROR: QA Issue: egt-media rdepends on gstreamer1.0-plugins-base-videoscale, but it isn't a build dependency? [build-deps]

Signed-off-by: Khem Raj <raj.khem@gmail.com>