at91bootstrap: fix build with no network
If a recipe sets SRCREV to ${AUTOREV}, bitbake tries
a git ls-remote. This breaks when a mirror is built
and BB_NO_NETWORK is set.
To work-around the issue, sets the revision for the git
version to a fix commit.

Fixes:

bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)}
which triggered exception NetworkAccess: Network access disabled through BB_NO_NETWORK
(or set indirectly due to use of BB_FETCH_PREMIRRORONLY) but access requested with command git -c core.fsyncobjectfiles=0
ls-remote git://github.com/linux4sam/at91bootstrap.git  (for url git://github.com/linux4sam/at91bootstrap.git)

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>