linux-yocto-custom: avoid PV going backwards on updates
Using SRCREV instead of SRCPV in PV will lead to errors like:

	ERROR: QA Issue: Package version for package kernel-module-lib80211-crypt-wep went backwards which would break package feeds from (0:3.10+ea25eb8a3ac9fcebc6c0d3b1c8e0c1223684d331-r4.1 to 0:3.10+68f2c28207fbc081f7be75fc01aca4827aa4a9f1-r5.1)

Which breaks upgrade paths.

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>