mchp-wireless-firmware: Use nonarch_base_libdir instead of hardcoding firmware path prefix
This helps the build with multilib
Fixes
ERROR: mchp-wireless-firmware-15.2-r0 do_package: QA Issue: mchp-wireless-firmware: Files/directories were installed but not shipped in any package:
  /lib
  /lib/firmware
  /lib/firmware/mchp
  /lib/firmware/mchp/wilc3000_ble_firmware.bin
  /lib/firmware/mchp/wilc3000_wifi_firmware.bin
  /lib/firmware/mchp/wilc1000_wifi_firmware.bin
  /lib/firmware/mchp/wilc3000_ble_firmware_no_rtc.bin

Signed-off-by: Khem Raj <raj.khem@gmail.com>