libegt: cleanup to comply with QA
There are no obvious reasons to override the PACKAGES variable and to
prepend the FILES variable.

Keep the default values of these variables. FILES has to be extended to
gather extra files as assets and xml files for the launcher.

It solves the QA issues, so it's no longer needed to skip some QA tests.

Error log:

ERROR: libplanes-1.0.3+gitAUTOINC+d897de598d-r0 do_package_qa: QA Issue:libplanes rdepends on libdrm-dev [dev-deps]
ERROR: libegt-1.7-r0 do_package_qa: QA Issue: libegt rdepends on cairo-dev [dev-deps]

Signed-off-by: Ludovic Desroches <ludovic.desroches@microchip.com>
Signed-off-by: Hari Prasath Gujulan Elango <Hari.PrasathGE@microchip.com>