recipes-utils: mxt-app: Add patch to fix gcc6 error
This commit adds a patch created by Alexandre Belloni to fix
a gcc6 error:
"../git/src/libmaxtouch/sysfs/sysfs_device.c:491:11: error: comparison
of constant '0' with boolean expression is always false [-Werror=bool-compare]"

While waiting for his pull-request to be accepted (see PL #53), the
patch is added in the recipe.

Upstream-Status: Submitted [http://github.com/atmel-maxtouch/mxt-app]
		 - By Alexandre Belloni
		 - See http://github.com/atmel-maxtouch/mxt-app/pull/53

Signed-off-by: Mylène Josserand <mylene.josserand@free-electrons.com>